name: cron_workflow

on:
  schedule:
    - cron: "0 8 * * 0-6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: job started
        run: echo The job is started
      - name: Current date and time
        run: date
      - name: Completion message
        run: echo Job completed successfully
